version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-node:
    # Build Node.js project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build the project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .next
            - package.json
            - package-lock.json

  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Install Netlify CLI
          command: npm install netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=.next
          environment:
            NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN
            NETLIFY_SITE_ID: $NETLIFY_SITE_ID

workflows:
  version: 2
  deploy_to_netlify:
    jobs:
      - build-node:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only:
                - main
